/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import automata.Aceptacion;
import automata.Analizar;
import javax.swing.JOptionPane;
import manejoarchivos.ManejoArchivos;
import patrones.Patrones;

/**
 *
 * @author GORDILLO G
 */
public class Inicial extends javax.swing.JFrame {

    /**
     * Creates new form Inicial
     */
    private NumeroLinea numeroLinea;
    private int contadorError = 0;
    private int contadorFinalErrores = 0;

    public Inicial() {
        initComponents();
        this.setTitle("Analizador lexico");
        GuardarTextoSinErrores.setVisible(false);
        recuento.setVisible(false);
        numeroLinea = new NumeroLinea(txt);
        jScrollPane1.setRowHeaderView(numeroLinea);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt = new javax.swing.JTextArea();
        GuardarTextoSinErrores = new javax.swing.JButton();
        analizar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCargar = new javax.swing.JMenu();
        menuLimpiar = new javax.swing.JMenu();
        recuento = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("ANALIZADOR LÉXICO");

        txt.setColumns(20);
        txt.setRows(5);
        jScrollPane1.setViewportView(txt);

        GuardarTextoSinErrores.setText("Guardar texto analizado sin errores");
        GuardarTextoSinErrores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarTextoSinErroresActionPerformed(evt);
            }
        });

        analizar.setText("Analizar");
        analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizarActionPerformed(evt);
            }
        });

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Buscar palabra:");

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(GuardarTextoSinErrores))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(analizar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnbuscar)))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(analizar)
                .addGap(18, 18, 18)
                .addComponent(GuardarTextoSinErrores)
                .addGap(26, 26, 26))
        );

        MenuCargar.setText("Cargar archivo");
        MenuCargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuCargarMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuCargar);

        menuLimpiar.setText("Eliminar texto");
        menuLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLimpiarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuLimpiar);

        recuento.setText("Recuento de lexemas");
        recuento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recuentoMouseClicked(evt);
            }
        });
        jMenuBar1.add(recuento);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarTextoSinErroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarTextoSinErroresActionPerformed

        ManejoArchivos manejo = new ManejoArchivos();
        String lectura = txt.getText();
        manejo.guardarArchivo(lectura);


    }//GEN-LAST:event_GuardarTextoSinErroresActionPerformed

    private void MenuCargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCargarMouseClicked
        // se muestra la opcion para cargar el archivo de texto
        ManejoArchivos manejo = new ManejoArchivos();
        manejo.leerArchivoLinea();
    }//GEN-LAST:event_MenuCargarMouseClicked

    private void analizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizarActionPerformed

        String txtIngresado = txt.getText();

        if (txtIngresado.length() > 0) {

            Aceptacion ne = new Aceptacion();
            ne.vaciarListas();
            //System.out.println("vacie las cosas incio");
            //se pide la ubicacion y nombre del archivo donde se guardaran las transiciones
            JOptionPane.showMessageDialog(null, "Selecciona una ubicacion para guardar la informacion de las transciciones");
            ManejoArchivos guardarMovimientos = new ManejoArchivos();
            String movimientos = "Movimientos";
            String pathMovimientos = guardarMovimientos.guardarArchivo(movimientos);

            //se pide la ubicacion y nombre del archivo donde se guardaran los posibles errores
            JOptionPane.showMessageDialog(null, "Selecciona una ubicacion para guardar los posibles errores");
            ManejoArchivos error = new ManejoArchivos();
            String errores = "Errores";
            String pathErrores = error.guardarArchivo(errores);
            error.AgregarAlArchivo(pathErrores + ".txt", "Cadena\t\t\t\t\tPosicion(fila,columna)");

            //se obtiene el texto que esta dentro del text area
            String lectura = txt.getText();
            //System.out.println("lectura hecha" + lectura);

            String[] lineas = lectura.split("\n");

            //se manda linea a linea el texto para analizarse
            for (int i = 0; i < lineas.length; i++) {
                // System.out.println("mande linea " + i);
                // se manda la linea, el numero de linea, el path del movimiento, el path de los errores 
                // y el path del archivo si no hay errrores
                Analizar analizar = new Analizar(lineas[i], i, pathMovimientos, pathErrores);
                contadorError = analizar.getError();
                //se cuenta el numero de errores obtenidos
                contadorFinalErrores = contadorFinalErrores + contadorError;

            }

            //si no hay errores en el texto analizado se crea el archivo con los tokens y se habilita
            //la opcion de generar la copia del texto que se analizo y no tiene erores
            if (contadorFinalErrores == 0) {

                JOptionPane.showMessageDialog(null, "Selecciona la ubicacion y nombre del archivo que contiene el reporte");
                ManejoArchivos ArchivoReporte = new ManejoArchivos();
                String Reporte = "Tipo token \t\t\tLexema\t\t\tPosicion(linea,columna)";
                String path = ArchivoReporte.guardarArchivo(Reporte);
                Aceptacion recuentoTotal = new Aceptacion(path);
                JOptionPane.showMessageDialog(null, "No se encontraron errores, se habilito la opcion del recuento de tokens");
                GuardarTextoSinErrores.setVisible(true);
                recuento.setVisible(true);

            } else {
                GuardarTextoSinErrores.setVisible(false);
                contadorFinalErrores = 0;
                recuento.setVisible(false);
                ne.vaciarListas();

            }

        }else{
            JOptionPane.showMessageDialog(null,"Ingresa texto para analizar");
        }

    }//GEN-LAST:event_analizarActionPerformed

    private void menuLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLimpiarMouseClicked
        txt.setText("");
    }//GEN-LAST:event_menuLimpiarMouseClicked

    private void recuentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recuentoMouseClicked
        JOptionPane.showMessageDialog(null, "Selecciona la ubicacion y nombre del archivo que contiene los tokens validos");
        ManejoArchivos ArchivoRecuento = new ManejoArchivos();
        String sinErrores = "Lexema\t\t\tTipo de token\t\t\tCantidad de repeticiones en el texto analizado";
        String path = ArchivoRecuento.guardarArchivo(sinErrores);
        Aceptacion recuentoTotal = new Aceptacion(path, 2);


    }//GEN-LAST:event_recuentoMouseClicked

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        String aBuscar = txtBuscar.getText();
        String textoTotal = txt.getText();

        if (textoTotal.length() > 0 && aBuscar.length()>0) {
            Patrones patron = new Patrones(aBuscar, textoTotal);
        } else {
            JOptionPane.showMessageDialog(null, "No hay texto para buscar lo solicitado");
        }


    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuardarTextoSinErrores;
    private javax.swing.JMenu MenuCargar;
    private javax.swing.JButton analizar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuLimpiar;
    private javax.swing.JMenu recuento;
    public static javax.swing.JTextArea txt;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
