/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import static Ventanas.Inicial.txt;
import automata.Aceptacion;
import automata.Analizar;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.event.CaretListener;
import manejoarchivos.ManejoArchivos;
import patrones.Patrones;

/**
 *
 * @author GORDILLO G
 */
public class Inicial extends javax.swing.JFrame {

    /**
     * Creates new form Inicial
     */
    private NumeroLinea numeroLinea;
    private int contadorError = 0;
    private int contadorFinalErrores = 0;

    public Inicial() {
        initComponents();
        this.setTitle("Analizador lexico");
        GuardarTextoSinErrores.setVisible(false);
        recuento.setVisible(false);
        numeroLinea = new NumeroLinea(txt);
        jScrollPane1.setRowHeaderView(numeroLinea);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt = new javax.swing.JTextArea();
        GuardarTextoSinErrores = new javax.swing.JButton();
        analizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        salida = new javax.swing.JTextArea();
        btnDeshacer = new javax.swing.JButton();
        btnRehacer = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        NuevoArchivoItem = new javax.swing.JMenu();
        CargarArchivoItem = new javax.swing.JMenuItem();
        nuevoArchivoItem = new javax.swing.JMenuItem();
        Guardar = new javax.swing.JMenu();
        itemCambios = new javax.swing.JMenuItem();
        menuGuardarComo = new javax.swing.JMenu();
        txtFile = new javax.swing.JMenuItem();
        pdfFile = new javax.swing.JMenuItem();
        WordFile = new javax.swing.JMenuItem();
        menuLimpiar = new javax.swing.JMenu();
        recuento = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("ANALIZADORES");

        txt.setColumns(20);
        txt.setRows(5);
        txt.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtCaretUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(txt);

        GuardarTextoSinErrores.setText("Guardar texto analizado sin errores");
        GuardarTextoSinErrores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarTextoSinErroresActionPerformed(evt);
            }
        });

        analizar.setText("Analizar");
        analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizarActionPerformed(evt);
            }
        });

        salida.setEditable(false);
        salida.setColumns(20);
        salida.setRows(5);
        jScrollPane2.setViewportView(salida);

        btnDeshacer.setText("Deshacer");
        btnDeshacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshacerActionPerformed(evt);
            }
        });

        btnRehacer.setText("Rehacer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnDeshacer)
                                .addGap(18, 18, 18)
                                .addComponent(btnRehacer)
                                .addGap(112, 112, 112)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(analizar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(GuardarTextoSinErrores)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDeshacer)
                            .addComponent(btnRehacer))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(analizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GuardarTextoSinErrores)
                .addGap(32, 32, 32))
        );

        NuevoArchivoItem.setText("Archivo");

        CargarArchivoItem.setText("Cargar archivo");
        CargarArchivoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArchivoItemActionPerformed(evt);
            }
        });
        NuevoArchivoItem.add(CargarArchivoItem);

        nuevoArchivoItem.setText("Nuevo archivo");
        nuevoArchivoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoArchivoItemActionPerformed(evt);
            }
        });
        NuevoArchivoItem.add(nuevoArchivoItem);

        jMenuBar1.add(NuevoArchivoItem);

        Guardar.setText("Guardar");
        Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarMouseClicked(evt);
            }
        });

        itemCambios.setText("Guardar cambios");
        itemCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCambiosActionPerformed(evt);
            }
        });
        Guardar.add(itemCambios);

        menuGuardarComo.setText("Guardar como");

        txtFile.setText("Documento de texto");
        txtFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFileActionPerformed(evt);
            }
        });
        menuGuardarComo.add(txtFile);

        pdfFile.setText("Documento PDF");
        pdfFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfFileActionPerformed(evt);
            }
        });
        menuGuardarComo.add(pdfFile);

        WordFile.setText("Documento Word");
        menuGuardarComo.add(WordFile);

        Guardar.add(menuGuardarComo);

        jMenuBar1.add(Guardar);

        menuLimpiar.setText("Eliminar texto");
        menuLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLimpiarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuLimpiar);

        recuento.setText("Recuento de lexemas");
        recuento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recuentoMouseClicked(evt);
            }
        });
        jMenuBar1.add(recuento);

        jMenu2.setText("Acerca de");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarTextoSinErroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarTextoSinErroresActionPerformed

        ManejoArchivos manejo = new ManejoArchivos();
        String lectura = txt.getText();
        manejo.guardarArchivo(lectura);


    }//GEN-LAST:event_GuardarTextoSinErroresActionPerformed

    private void analizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizarActionPerformed
        
        String txtIngresado = txt.getText();

        if (txtIngresado.length() > 0) {

            Aceptacion ne = new Aceptacion();
            ne.vaciarListas();
            //System.out.println("vacie las cosas incio");
            //se pide la ubicacion y nombre del archivo donde se guardaran las transiciones
            JOptionPane.showMessageDialog(null, "Selecciona una ubicacion para guardar la informacion de las transciciones");
            ManejoArchivos guardarMovimientos = new ManejoArchivos();
            String movimientos = "Movimientos";
            String pathMovimientos = guardarMovimientos.guardarArchivo(movimientos);

            //se pide la ubicacion y nombre del archivo donde se guardaran los posibles errores
            JOptionPane.showMessageDialog(null, "Selecciona una ubicacion para guardar los posibles errores");
            ManejoArchivos error = new ManejoArchivos();
            String errores = "Errores";
            String pathErrores = error.guardarArchivo(errores);
            error.AgregarAlArchivo(pathErrores + ".txt", "Cadena\t\t\t\t\tPosicion(fila,columna)");

            //se obtiene el texto que esta dentro del text area
            String lectura = txt.getText();
            //System.out.println("lectura hecha" + lectura);

            String[] lineas = lectura.split("\n");

            //se manda linea a linea el texto para analizarse
            for (int i = 0; i < lineas.length; i++) {
                // System.out.println("mande linea " + i);
                // se manda la linea, el numero de linea, el path del movimiento, el path de los errores 
                // y el path del archivo si no hay errrores
                Analizar analizar = new Analizar(lineas[i], i, pathMovimientos, pathErrores,lineas.length);
                contadorError = analizar.getError();
                //se cuenta el numero de errores obtenidos
                contadorFinalErrores = contadorFinalErrores + contadorError;

            }

            //si no hay errores en el texto analizado se crea el archivo con los tokens y se habilita
            //la opcion de generar la copia del texto que se analizo y no tiene erores
            if (contadorFinalErrores == 0) {

                JOptionPane.showMessageDialog(null, "Selecciona la ubicacion y nombre del archivo que contiene el reporte");
                ManejoArchivos ArchivoReporte = new ManejoArchivos();
                String Reporte = "Tipo token \t\t\tLexema\t\t\tPosicion(columna,linea)";
                String path = ArchivoReporte.guardarArchivo(Reporte);
                Aceptacion recuentoTotal = new Aceptacion(path);
                JOptionPane.showMessageDialog(null, "No se encontraron errores, se habilito la opcion del recuento de tokens");
                GuardarTextoSinErrores.setVisible(true);
                recuento.setVisible(true);

            } else {
                GuardarTextoSinErrores.setVisible(false);
                contadorFinalErrores = 0;
                recuento.setVisible(false);
                ne.vaciarListas();

            }

        }else{
            JOptionPane.showMessageDialog(null,"Ingresa texto para analizar");
        }

    }//GEN-LAST:event_analizarActionPerformed

    private void menuLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLimpiarMouseClicked
        txt.setText("");
    }//GEN-LAST:event_menuLimpiarMouseClicked

    private void recuentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recuentoMouseClicked
        JOptionPane.showMessageDialog(null, "Selecciona la ubicacion y nombre del archivo que contiene los tokens validos");
        ManejoArchivos ArchivoRecuento = new ManejoArchivos();
        String sinErrores = "Lexema\t\t\tTipo de token\t\t\tCantidad de repeticiones en el texto analizado";
        String path = ArchivoRecuento.guardarArchivo(sinErrores);
        Aceptacion recuentoTotal = new Aceptacion(path, 2);


    }//GEN-LAST:event_recuentoMouseClicked

    private void txtCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtCaretUpdate
     
        
    }//GEN-LAST:event_txtCaretUpdate

    private void GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarMouseClicked

    private void itemCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCambiosActionPerformed
        System.out.println("Hlla");
    }//GEN-LAST:event_itemCambiosActionPerformed

    private void txtFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFileActionPerformed

    private void pdfFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdfFileActionPerformed

    private void CargarArchivoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArchivoItemActionPerformed
        // se muestra la opcion para cargar el archivo de texto
        ManejoArchivos manejo = new ManejoArchivos();
        manejo.leerArchivoLinea();
    }//GEN-LAST:event_CargarArchivoItemActionPerformed

    private void nuevoArchivoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoArchivoItemActionPerformed
        
    }//GEN-LAST:event_nuevoArchivoItemActionPerformed

    private void btnDeshacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshacerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeshacerActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        AcercaDe info = new AcercaDe();
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CargarArchivoItem;
    private javax.swing.JMenu Guardar;
    private javax.swing.JButton GuardarTextoSinErrores;
    private javax.swing.JMenu NuevoArchivoItem;
    private javax.swing.JMenuItem WordFile;
    private javax.swing.JButton analizar;
    private javax.swing.JButton btnDeshacer;
    private javax.swing.JButton btnRehacer;
    private javax.swing.JMenuItem itemCambios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu menuGuardarComo;
    private javax.swing.JMenu menuLimpiar;
    private javax.swing.JMenuItem nuevoArchivoItem;
    private javax.swing.JMenuItem pdfFile;
    private javax.swing.JMenu recuento;
    private javax.swing.JTextArea salida;
    public static javax.swing.JTextArea txt;
    private javax.swing.JMenuItem txtFile;
    // End of variables declaration//GEN-END:variables
}
